#ifndef _CTRLIDS_H_
#define _CTRLIDS_H_

/*
** This file is auto-generated by the MX Form Manager tool.
** Do not modify the contents of this file by hand!
*/

/* Control IDs for Form waiver-title */
#define waiver-title_LBL_1               10
#define waiver-title_BTN_1               1
#define waiver-title_BTN_2               2
#define waiver-title_LBL_2               11
#define waiver-title_TXT_1               12

/* Control IDs for Form waiver-cancel */
#define waiver-cancel_LBL_1              1

/* Control IDs for Form waiver-complete */
#define waiver-complete_LBL_1            1
#define waiver-complete_LBL_2            2

/* Control IDs for Form waiver-personal-info-conf */
#define waiver-personal-info-conf_LBL_1  30
#define waiver-personal-info-conf_LBL_2  13
#define waiver-personal-info-conf_LBL_3  12
#define waiver-personal-info-conf_LBL_4  11
#define waiver-personal-info-conf_LBL_5  10
#define waiver-personal-info-conf_LBL_6  17
#define waiver-personal-info-conf_LIN_1  7
#define waiver-personal-info-conf_LBL_7  16
#define waiver-personal-info-conf_LBL_20 15
#define waiver-personal-info-conf_LBL_21 14
#define waiver-personal-info-conf_BTN_1  1
#define waiver-personal-info-conf_BTN_2  2

/* Control IDs for Form waiver-minor-info-conf */
#define waiver-minor-info-conf_LBL_1     14
#define waiver-minor-info-conf_LBL_2     11
#define waiver-minor-info-conf_LBL_3     10
#define waiver-minor-info-conf_LBL_4     13
#define waiver-minor-info-conf_LBL_5     12
#define waiver-minor-info-conf_BTN_1     1
#define waiver-minor-info-conf_BTN_2     2
#define waiver-minor-info-conf_LBL_6     16

/* Control IDs for Form idle */
#define idle_IMG_1                       1

/* Control IDs for Form payment-swipe-prompt */
#define payment-swipe-prompt_IMG_1       1
#define payment-swipe-prompt_LBL_2       4
#define payment-swipe-prompt_LBL_3       5

/* Control IDs for Form payment-method-selection */
#define payment-method-selection_IMG_1   1
#define payment-method-selection_LBL_1   2
#define payment-method-selection_BTN_1   3
#define payment-method-selection_BTN_2   5
#define payment-method-selection_BTN_3   7

/* Control IDs for Form payment-processing */
#define payment-processing_IMG_1         1
#define payment-processing_LBL_1         2

/* Control IDs for Form waiver-signature-page */
#define waiver-signature-page_LBL_1      10
#define waiver-signature-page_BTN_1      2
#define waiver-signature-page_BTN_2      1
#define waiver-signature-page_TXT_1      12
#define waiver-signature-page_LBL_2      11

#endif /* _CTRLIDS_H_ */
