#ifndef _CB_FNS_H_
#define _CB_FNS_H_

/*
** This file is auto-generated by the MX Form Manager tool.
** Do not modify the contents of this file by hand!
*/

void waiver-title_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-title_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-title_TXT_1_OnUp(char* strFormName, int iControlID, void* pData);
void waiver-title_TXT_1_OnDown(char* strFormName, int iControlID, void* pData);
void waiver-personal-info-conf_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-personal-info-conf_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-minor-info-conf_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-minor-info-conf_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void idle_IMG_1_OnTouch(char* strFormName, int iControlID, void* pData);
void payment-swipe-prompt_IMG_1_OnTouch(char* strFormName, int iControlID, void* pData);
void payment-method-selection_IMG_1_OnTouch(char* strFormName, int iControlID, void* pData);
void payment-method-selection_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void payment-method-selection_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void payment-method-selection_BTN_3_OnClick(char* strFormName, int iControlID, void* pData);
void payment-processing_IMG_1_OnTouch(char* strFormName, int iControlID, void* pData);
void waiver-signature-page_BTN_1_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-signature-page_BTN_2_OnClick(char* strFormName, int iControlID, void* pData);
void waiver-signature-page_TXT_1_OnUp(char* strFormName, int iControlID, void* pData);
void waiver-signature-page_TXT_1_OnDown(char* strFormName, int iControlID, void* pData);

#endif /* _CB_FNS_H_ */
