/*
** This file is auto-generated by the MX Form Manager tool.
** Do not modify the contents of this file by hand!
*/

#include "cb_fns.h"

typedef void (*Event_Callback_Function)(char *pszFormName, int iControlID, void *pData);

Event_Callback_Function cb_Functions[] = 
{
    0,
    waiver-title_BTN_1_OnClick,
    waiver-title_BTN_2_OnClick,
    waiver-title_TXT_1_OnUp,
    waiver-title_TXT_1_OnDown,
    waiver-personal-info-conf_BTN_1_OnClick,
    waiver-personal-info-conf_BTN_2_OnClick,
    waiver-minor-info-conf_BTN_1_OnClick,
    waiver-minor-info-conf_BTN_2_OnClick,
    idle_IMG_1_OnTouch,
    payment-swipe-prompt_IMG_1_OnTouch,
    payment-method-selection_IMG_1_OnTouch,
    payment-method-selection_BTN_1_OnClick,
    payment-method-selection_BTN_2_OnClick,
    payment-method-selection_BTN_3_OnClick,
    payment-processing_IMG_1_OnTouch,
    waiver-signature-page_BTN_1_OnClick,
    waiver-signature-page_BTN_2_OnClick,
    waiver-signature-page_TXT_1_OnUp,
    waiver-signature-page_TXT_1_OnDown,
};
